verstion: 0.1
phases:
  install:
    commands:
      - npm install
      - npm run build
      - aws s3 cp build s3://react-mui --recursive --exclude 'index.html'
      - aws s3 cp build/index.html s3://react-mui